### ISSUE TITLE
[Major] The search bar isn't functional

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/b-team#61]
Description: When I search for something using the search bar on the top of the page it doesn't work.

Steps to Reproduce:
1. Go to Shop page from navbar
2. Type into search bar
3. Apply search either by pressing search button or pressing enter

Expected: I expected it to show up search results for the keywords.
Actual: It displays an error page.
Tested on ChromeVersion 96.0.4664.55 (Official Build) on MacOs Catalina

**Comment by swaleha6** [comment]
valid issue we were already aware of, going to work on it through the next development sprint

**Comment by Vivianngu3** [comment]
Last Duplicate: https://github.com/info442-aut21/b-team/issues/70

**Comment by swaleha6** [comment]
pr - https://github.com/info442-aut21/b-team/pull/105
