### ISSUE TITLE
[minor] ted talk video automatically plays

### ISSUE THREAD

**Issue by njkpark** [info442-aut21/b-team#62]
While scrolling down the homepage, the video automatically plays without any prompt. A user would have to scroll back up/down to pause the video.

Environment: Iphone 12

steps to reproduce: scroll down until video shows on screen.

 Expected result: video only plays when user clicks on the video

Actual result: video plays regardless of user peompt

**Comment by angelinapoltavskiy** [comment]
we could not reproduce this issue.. don't see anything to fix

**Comment by cherimarie** [comment]
@angelinapoltavskiy did you check on multiple browsers? Some browsers now block "autoplay" feature, but not all. If this is a feature of the video you're embedding, you may not have control over autoplay, but if you do, you should definitely disable it.
