### ISSUE TITLE
[Major] The filters aren't working

### ISSUE THREAD

**Issue by palashgujrathi** [info442-aut21/b-team#63]
Description: When I use the filter to select the country or any other filter, it doesn't work

Steps to Reproduce:
1. Go to Shops Page from NavBar
2. Apply Filters on Lefthand side

Expected: I expected it to show up searches for those particular filter.
Actual: No response
Tested on Safari Version 15.1 (17612.2.9.1.20) on macOS Monterey.

**Comment by angelinapoltavskiy** [comment]
valid issue we were already aware of, going to work on it through the next development sprint
