### ISSUE TITLE
[Minor] Website Icon Cannot Navigate To Homepage

### ISSUE THREAD

**Issue by nsnatthapat** [info442-aut21/b-team#64]
Description: The website icon is not functional and does not allow for navigation back to home

Environment: Google Chrome Version 95.0.4638.69 (Official Build) (x86_64) on MacOS Monterey

Steps to Reproduce: Click on Branding Icon on Top Left

Actual Result: No Result

Expected Result: Navigate to homepage

**Comment by swaleha6** [comment]
valid issue we were already aware of, going to work on it through the next development sprint

**Comment by Vivianngu3** [comment]
Last Duplicate: https://github.com/info442-aut21/b-team/issues/85
