### ISSUE TITLE
[Major] The filters are not functional

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/b-team#65]
Description: Whenever I use the checkboxes on the left to filter the cards, no changes are made to the cards.
Expected: Whenever checked the filters would apply and the filtered cards would show up.
Actual: Nothing happens when I check one of the filters.
Tested on Chrome Version 96.0.4664.55 (Official Build) on macOS Catalina

**Comment by angelinapoltavskiy** [comment]
Duplicate issue: this issue was created before your's
https://github.com/info442-aut21/b-team/issues/63#issue-1060396803

**Comment by angelinapoltavskiy** [comment]
issue was fixed on PR #97

**Comment by swaleha6** [comment]
pr - https://github.com/info442-aut21/b-team/pull/97
