### ISSUE TITLE
[Minor] Clicking on the store name does not link me to the store

### ISSUE THREAD

**Issue by Preciousstowers** [info442-aut21/b-team#66]
When I click the store name, it does not link me to the store, instead I have to click on the picture for this functionality to work. 

Environment: Google Chrome v96.0.4664.55 in Mac OS Big Sur

Steps: Click on the store name on the shop's page. 
Actual result: Clicked on the store name and nothing appeared. 
Expected result: Click on the store name and get linked to the store on a new page.

**Comment by swaleha6** [comment]
valid issue we were already aware of, going to work on it through the next development sprint

**Comment by Vivianngu3** [comment]
Last Duplicate: https://github.com/info442-aut21/b-team/issues/76
