### ISSUE TITLE
[Minor] Search field becomes almost invisible at a smaller window size

### ISSUE THREAD

**Issue by Skylitmoon** [info442-aut21/b-team#67]
This was tested on MacBook 15 inch on MacOS Monterey and Google Chrome Version 96.0.4664.45. 

1. Navigate to the shops tab
2. Set browser window size to take half of the screen
Expected result: Full length search bar and icon
Actual result: Search field almost invisible alongside with the icon

**Comment by swaleha6** [comment]
valid issue we were already aware of, going to work on it through the next development sprint

**Comment by Vivianngu3** [comment]
Last duplicate: https://github.com/info442-aut21/b-team/issues/73

**Comment by angelinapoltavskiy** [comment]
fixed issue
