### ISSUE TITLE
[Minor] form submission still has inputted fields after sending

### ISSUE THREAD

**Issue by njkpark** [info442-aut21/b-team#68]
After giving email and message, pressing submit sends the message and success indicator, however, when we “go back” as prompted, the email and message is still in the field.

Environment: Apple iphone 12 on Chrome/Safari

Steps to reproduce: input email and message, click submit, then click “go back”, email and message will still appear on the screen.

Expected result: the email and message would not reappear-should be empty

actual result: fields are still being occupied (text is present)

**Comment by swaleha6** [comment]
Wontfix - we used a third party form making service so we can’t fix this
