### ISSUE TITLE
Major: Search button

### ISSUE THREAD

**Issue by manyaj57** [info442-aut21/b-team#70]
Description: Search button leads to error page (regardless if text is entered into search bar or not)

Steps to Reproduce:

1. Go to Shop page from navbar
2. Click blue search button with magnifying glass
Expected: I expected the page to just reload or display an "please enter a search criteria" message
Actual: It displays a 404 error page.
Tested on ChromeVersion 96.0.4664.55 (Official Build) on MacOs Catalina

**Comment by swaleha6** [comment]
Duplicate - https://github.com/info442-aut21/b-team/issues/61
