### ISSUE TITLE
[Minor] Misalignment of Website Mission on Smaller Windows and Hamburger Menu Options Alignment

### ISSUE THREAD

**Issue by julianedelossantos** [info442-aut21/b-team#71]
The way the mission statement fits onto the page on smaller windows and potentially on a mobile device is not consistent with desktop. It seems to be right-aligned as the logo "Branding" takes up the space on the left. When the hamburger menu is opened, the tabs are not centered, and the mission statement is then pushed to the left. The hamburger menu items are somewhat left-aligned when opened on a smaller browser.

Environment: Windows 11 - Brave Browser: Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

To reproduce this issue, you must open up the website's home screen and reduce the width of your browser window as far as it can go. Is for the logo to be more aligned with the upper left-hand corner and across from the hamburger menu and the mission statement in the same spot with the "Decrease waste," centered on the page. You can see the 2nd part of this when clicking on the hamburger menu and the drop-down opens up to push the mission statement to the left and display options that aren't centered under the lines provided.

The results I was expecting was to have an unmovable mission statement under the menu options and logo under this smaller window screen as well as consistent, centered menu options under the lines provided when the hamburger menu is opened.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/72470963/142904144-a7d72824-debf-400d-9192-de5ee8f0f4c6.png">
<img width="359" alt="image" src="https://user-images.githubusercontent.com/72470963/142905738-e5c838f1-f315-4b3a-b609-a53a3097d4df.png">

**Comment by swaleha6** [comment]
valid issue, going to work on it through the next development sprint

**Comment by Vivianngu3** [comment]
Last Duplicate: https://github.com/info442-aut21/b-team/issues/77

**Comment by angelinapoltavskiy** [comment]
fixed on PR #102
