### ISSUE TITLE
[Minor] Error message after submitting empty contact us form

### ISSUE THREAD

**Issue by matthewputra** [info442-aut21/b-team#72]
Environment: Version 95.0.4638.69 (Official Build) (x86_64)
Steps: don't fill anything in the contact us forms and submit it. It will display an error message that it cannot be sent. 
Expected result: an error message that can easily be understood by the users
Actual result: an error message that is hard to understand. Users will not understand what did it mean by placing the "name" attribute and "required" property.
Error message: (Make sure you have placed the "name" attribute in all your form elements. Also, to prevent empty form submissions, see the "required" property.)

**Comment by Vivianngu3** [comment]
We are aware of this and will not be able to fix because we are using a third party form

**Comment by Vivianngu3** [comment]
last duplicate: https://github.com/info442-aut21/b-team/issues/90
