### ISSUE TITLE
Minor: Search bar sizing on smaller screens

### ISSUE THREAD

**Issue by manyaj57** [info442-aut21/b-team#73]
Description: At a smaller screen size the search bar breaks (either blue button is split from the bar or search bar is cut off)

Steps to Reproduce:

1. Go to Shop page from navbar
2. adjust screen size 

Expected: I expected the search size to responsively adjust to the new screen sizes
Actual: the search bar breaks / is too small to be readable
Tested on ChromeVersion 96.0.4664.55 (Official Build) on MacOs Catalina

**Comment by angelinapoltavskiy** [comment]
were able to reproduce, going to fix in next sprint

**Comment by Vivianngu3** [comment]
https://github.com/info442-aut21/b-team/issues/67
