### ISSUE TITLE
[Enhancement] Hard to navigate back to shops page after going to details page

### ISSUE THREAD

**Issue by victoriathegr8** [info442-aut21/b-team#74]
Currently, it isn't intuitive to go back to the complete shops page after clicking on the details of one shop. The only way is to click the shops link on the nav bar.
Feature request: place a back button on each details page that redirects the user back to the shops page.

**Comment by swaleha6** [comment]
won’t fix - user can use back button on browser and also the shops page link is in the navbar which is always present
