### ISSUE TITLE
[Feature Request] Make Filter Checkboxes Bigger

### ISSUE THREAD

**Issue by IamSuperB4** [info442-aut21/b-team#75]
Windows 11:
Google Chrome: Version 96.0.4664.45

As an aside from the issue that the filters don't work, the checkboxes for the filter are very small, I would like them to be bigger. The entire filter menu could use some increased sizing and take up the entire left portion of the page since nothing else is there anyway.

![image](https://user-images.githubusercontent.com/16829246/142907875-c3b6f92f-57a4-4136-a977-5260a66292c6.png)

**Comment by IamSuperB4** [comment]
Forgot to put a reason. The filter options can be hard to see and hard to click on.

**Comment by swaleha6** [comment]
This passed our accessibility testing, so we won’t fix this

**Comment by swaleha6** [comment]
We will fix this in our development sprint

**Comment by Vivianngu3** [comment]
last duplicate: https://github.com/info442-aut21/b-team/issues/84

**Comment by angelinapoltavskiy** [comment]
fixed issue on PR #101
