### ISSUE TITLE
[Feature Request] Make Entire Shop Card Clickable

### ISSUE THREAD

**Issue by IamSuperB4** [info442-aut21/b-team#76]
Windows 11:
Google Chrome: Version 96.0.4664.45

Clicking on the image on each card for the shop takes you to the site for that card. However, clicking below the image but still in the card does not take you to the shop's page. I would like the entire card to take you to the page.

**Comment by IamSuperB4** [comment]
Forgot to put a reason. It would be a nicety to be able to click on the entire card. Sometimes I like to click the text of the card and not the image, so I would need to click again on the image for it to take me to where I want to go.

**Comment by swaleha6** [comment]
https://github.com/info442-aut21/b-team/issues/66 Duplicate
