### ISSUE TITLE
[Minor] Navbar misaligned with the hamburger menu on Mobile Screen

### ISSUE THREAD

**Issue by vanessasgh** [info442-aut21/b-team#77]
Description: The website title and first text letter(motto) seemed to be in one-line and when the hamburger is opened, it pushes the website name and the first text letter to the side.

Steps to reproduce: use your phone and navigate to the home page. Click the hamburger menu on the top right to see how the view changes.

I expected the website title to consistently be on the top left and the hamburger menu on the top right, with the hamburger menu items displaying over the content, and not disrupting or changing any of the current content of the website. The first text(I think is the motto), should be on the bottom and middle aligned, similar to the other items in the website.

**Comment by sershon** [comment]
Additional bug: On mobile when you click "Find Shops!" on the main page, the search button icon appears to be clipped off. I would expect it to be alligned in someway with the "branding heading" and the search bar. I'm on a Samsung S21 running Google Chrome on Android 12. Here is what it looks like on my scree
![Screenshot_20211122-095050_Chrome](https://user-images.githubusercontent.com/72484672/142910762-10f8d5b1-52b6-47f6-b134-dd97cf7f6339.jpeg)
n:

**Comment by angelinapoltavskiy** [comment]
Were able to reproduce the issue, will be working on fixing this during the next development sprint

**Comment by Vivianngu3** [comment]
https://github.com/info442-aut21/b-team/issues/71
