### ISSUE TITLE
[Feature Request] Have name of the shops take you to additional page instead of only image

### ISSUE THREAD

**Issue by naishg** [info442-aut21/b-team#78]
Although clicking on the cards do take you to an additional page, it only really works when you click on the image. A possible change that you could add is to click on the name of the shop and have that take you to he additional page instead of it being only the image

**Comment by angelinapoltavskiy** [comment]
will develop this request in the next development sprint

**Comment by talajune** [comment]
duplicate https://github.com/info442-aut21/b-team/issues/66
