### ISSUE TITLE
[Minor] misalignment of search bar and search button

### ISSUE THREAD

**Issue by ayun6** [info442-aut21/b-team#80]
On the Shops page of the Branding website, the search bar and search button are misaligned. 
Environment: Chrome 95.0.4638.69 on MacOS Big Sur
Expected: Alignment of search bar and search button
Actual: Misalignment

<img width="301" alt="Screen Shot 2021-11-22 at 9 43 09 AM" src="https://user-images.githubusercontent.com/72246542/142909623-907bbd3d-038b-4e88-9e72-41e3e610e43b.png">

**Comment by talajune** [comment]
Angelina was planning on fixing this anyway

**Comment by Vivianngu3** [comment]
https://github.com/info442-aut21/b-team/issues/71

**Comment by angelinapoltavskiy** [comment]
fixed under issue of #67 under AP-67 branch
