### ISSUE TITLE
[Minor] Misalignment of the cards on the shops tab

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/b-team#81]
Description: The cards are usually aligned 4 in a row format, but this format is broken down for the last row.
Expected: 4 cards displayed in each row.
Actual: The last row has one card displayed in the middle which is not properly aligned with the others.
Tested on Chrome Version 96.0.4664.55 (Official Build) on MacOs Catalina.
<img width="1440" alt="Screen Shot 2021-11-22 at 9 59 30 AM" src="https://user-images.githubusercontent.com/56050100/142911827-03ad2baa-43db-4a53-8690-cdd4d21ed568.png">

**Comment by swaleha6** [comment]
Won’t fix - we centered our shop cards in rows in a flexbox as our design decision
