### ISSUE TITLE
[Enhancement] On mobile, the text on the filters should be bigger for better readability

### ISSUE THREAD

**Issue by Skylitmoon** [info442-aut21/b-team#84]
Tested on MacOS Monterey and Google Chrome Version 96.0.4664.45. The text is a bit too small when the window size is set to mobile. Increasing the size of the text in the Filter box would increase readability.

**Comment by angelinapoltavskiy** [comment]
will fix sizing of text in development sprint

**Comment by angelinapoltavskiy** [comment]
duplicate of #75
