### ISSUE TITLE
[Feature Request] Clicking on the logo 'branding' and have that take you to the home page

### ISSUE THREAD

**Issue by naishg** [info442-aut21/b-team#85]
Although there is already a button that says home which takes you to the home page, because the word 'branding' is already there it seems useless. Therefore, making it clickable will not only give it some use but it will also help to make the website easier to navigate.

**Comment by swaleha6** [comment]
This is valid, we will fix it in the development sprint

**Comment by Vivianngu3** [comment]
https://github.com/info442-aut21/b-team/issues/64

**Comment by swaleha6** [comment]
pr - https://github.com/info442-aut21/b-team/pull/109
