### ISSUE TITLE
[Enhancement] Recommend users to add sustainable fashion brands in the Contact Us text explanation

### ISSUE THREAD

**Issue by Preciousstowers** [info442-aut21/b-team#86]
There are many companies that need a solid platform to market against fast fashion brands. Clearly recommending users like "Know a sustainable brand? Let us know" in the "Contact us" form would allow this website to grow faster and even help small businesses.

**Comment by swaleha6** [comment]
We will add this in our development sprint

**Comment by angelinapoltavskiy** [comment]
fixed issue on PR #100
