### ISSUE TITLE
[Minor] Form allows submission without all fields being filled

### ISSUE THREAD

**Issue by aramos10-1863966** [info442-aut21/b-team#88]
Description: The form for contacting has two fields, email and message. The form requires the email be an email which is great, however, I can submit a form with a message and no email or an email but no message. This leads to spam and receiving messages that cannot be replied to as we would not have an email to reply back to the user.

Expectation: All fields are required to be filled for the form to be submitted

Environment: Microsoft Edge Version 96.0.1054.29

**Comment by Vivianngu3** [comment]
https://github.com/info442-aut21/b-team/issues/72
