### ISSUE TITLE
[Enhancement] Navigating to a shop's site takes users away from your webpage

### ISSUE THREAD

**Issue by aramos10-1863966** [info442-aut21/b-team#89]
Description: After I chose to look at the Patagonia card and see more information, I clicked on the link to navigate to their shop. This opened in my current window and took me away from your webpage when I might have wanted to continue exploring other shops. After looking at Patagonia's site.

Expectation: When navigating to a shop's webpage, open the shop in a new tab/window rather than in the current one so that your web app remains open on the user's machine.

Environment: Microsoft Edge Version 96.0.1054.29

**Comment by swaleha6** [comment]
Valid issue, will fix in the development sprint

**Comment by angelinapoltavskiy** [comment]
fixed issue #89

**Comment by swaleha6** [comment]
https://github.com/info442-aut21/b-team/pull/94
