### ISSUE TITLE
[Enhancement] Form Submission Pop Up on Empty Submission

### ISSUE THREAD

**Issue by vanessasgh** [info442-aut21/b-team#90]
In the contact us form, if the fields are empty and you click the submit button, it brings you to another page from "form spree" and talks about how the "name" attribute needs to be filled and all. I expected the form to just give a "cannot be empty" writing and et the user stay on the page, instead of letting the user submit the form, direct them to another page where it then says that it cannot be submitted successfully. The users would then need to go back to the previous page manually to go back to where they were.

**Comment by Vivianngu3** [comment]
https://github.com/info442-aut21/b-team/issues/72
