### ISSUE TITLE
[Enhancement] Change Fixed Header to a Footer or add Navbar Elements to Fixed Header

### ISSUE THREAD

**Issue by jovecalimlim** [info442-aut21/b-team#91]
Description: Add navigation elements to the fixed header or change the fixed header to a footer so the slogan appears at the bottom of the page.

Explanation: The current fixed header has no functionality other than showing a slogan for the website. Adding navbar elements would make having this fixed header a bit useful or moving it to the footer would move it to a spot on the page that wouldn't be one of the first things the user notices that they can't interact with.

**Comment by talajune** [comment]
design decision on our part to not fix
