### ISSUE TITLE
[Enhancement] Increase text size throughout the site

### ISSUE THREAD

**Issue by jovecalimlim** [info442-aut21/b-team#92]
Description: Increase the text size on the Shops page filters, About us mission statement, and home page.

Explanation: Especially on the Shops page filters, I thought the text size was a bit small and hard to read without having to move closer to my screen. Increasing the text size on these pages would improve readability.

**Comment by talajune** [comment]
We passed all of our accessibility tests and didn't get any comments or notes about text size.

**Comment by angelinapoltavskiy** [comment]
we

**Comment by angelinapoltavskiy** [comment]
fixed on AP-87 branch
